enable user-local default mappings
kana/vim-gf-user pull request #6
Opened 2024-04-17 08:27 UTC by Konfekt

The gf-user plug-in has as one main implementation the gf-diff plug-in which is very useful in diffs, but maybe less in other file types. With this modification, the default mappings can be added buffer-locally, for example by

let g:gf_user_no_default_key_mappings = 1
autocmd vimrc FileType git,gitcommit,diff GfUserDefaultKeyMappings! buffer

2024-04-17 08:28 UTC, Konfekt commented
Please let me know if this sounds reasonable to you, and documentation may be added.

2024-04-17 21:48 UTC, kana requested changes
Thank you for the pull request. It sounds reasonable for me. I'll be happy to merge this when the following points are resolved.

2024-04-17 21:48 UTC, kana commented on plugin/gf/user.vim
> +  let modifier .= substitute(a:args, '\S\+', '<\0>', 'g')
```suggestion
  let modifier .= a:args
```

I prefer just appending `a:args` as is.  It makes code using the command look more intuitive for users familiar with key mapping notation.

```vim
" Before
GfUserDefaultKeyMappings! buffer

" After
GfUserDefaultKeyMappings! <buffer>
```

2024-04-17 21:48 UTC, kana commented on plugin/gf/user.vim
> +command! -bang -nargs=* GfUserDefaultKeyMappings
```suggestion
command! -bang -bar -nargs=* GfUserDefaultKeyMappings
```

`-bar` should not be dropped unless the command requires `|` as a part of its argument.

2024-04-18 03:49 UTC, Konfekt commented
Thank you very much, I hope to have addressed all points raised

2024-04-18 06:36 UTC, merged

2024-04-18 06:47 UTC, Konfekt commented
For what it's worth, here's [a next best try](https://github.com/drmikehenry/vimfiles/blob/a89a26ab0f39469691f50d2b41a5cffdeecd6e68/vimrc#L3209) that could be applied outside files taken care of by gf-user plugins